title: SES 5215
logo: images/scatter.jpg
description: This site contains resources for the Quantitative Methods course taught by Carole Turley Voulgaris at the Harvard Graduate School of Design.
show_downloads: false
theme: jekyll-theme-minimal
