---
title: "Data visualization Notes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Sample Data Set

```{r, message=FALSE}
library(tidyverse)
library(knitr)

x1 <- rnorm(10000, mean = 100, sd = 20)
x2 <- rnorm(10000, mean = 150, sd = 25)
x3n <- runif(10000, min = 0, max = 1) 
x3 <- case_when(x3n < 0.3 ~ "A",
                x3n < 0.5 ~ "B",
                x3n < 0.9 ~ "C",
                x3n < 0.95 ~ "D",
                TRUE ~ "E")

data <- tibble(x1 = x1,
               x2 = x2, 
               x3 = x3,
               A = x3 == "A",
               B = x3 == "B",
               C = x3 == "C",
               D = x3 == "D",
               E = x3 == "E",
               y = 0.3*x1 + 0.6*x2 + B*20 + C*15 + D*10 + E*5)

head(data) |>
  kable()
```

# Scatterplot

## Relationship between two continuous variables

```{r}
ggplot(data) +
  geom_point(aes(x = x1, y = y),
             alpha = 0.2) +
  theme_bw()
```

## Relationship between a continuous and categorical variables

```{r}
ggplot(data) +
  geom_point(aes(x = x3, y = y),
             alpha = 0.2,
             position = "jitter")
```

## Distribution of a continuous variable

```{r}
ggplot(data) +
  geom_jitter(aes(x = x1, y = 1),
             alpha = 0.2) +
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank())
```

# Histogram

```{r, echo=FALSE}
ggplot(data) +
  geom_histogram(aes(x = x1),
                 binwidth = 5)
```

# Density curve

```{r, echo=FALSE}
ggplot(data) +
  geom_density(aes(x = x1))
```


# Violin plot

```{r}
ggplot(data) +
  geom_violin(aes(x = x3,
                  y = y))+
  geom_point(aes(x = x3, y = y),
             alpha = 0.1,
             position = "jitter")
```


# Tree map

```{r}
library(treemapify)

data_summary <- data |>
  group_by(x3) |>
  summarise(count = n())

ggplot(data_summary) +
  geom_treemap(aes(area = count,
                   fill = x3)) +
  geom_treemap_text(aes(area = count,
                        label = x3)) +
  scale_fill_brewer(type = "qual",
                    guide = "none")
```

